### ISSUE TITLE
Can't figure out how to run it in docker

### ISSUE THREAD

**Issue by drforse** [tonutils/reverse-proxy#5]
Hello. I can't figure out how to run it in docker. Could please someone help me?

Dockerfile
```
FROM alpine
WORKDIR /app
COPY tonutils-reverse-proxy-linux-amd64 /app/
CMD ./tonutils-reverse-proxy-linux-amd64
```
docker-compose.yml
```
version: '3'
services:
  ton-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.json:/app/config.json
    ports:
      - 9082:9082
    restart: unless-stopped
    networks:
      - proxynet
networks:
  proxynet:
    name: tor_nginx
```
config.json
```
{
        "proxy_pass": "nginx",
        "private_key": "<private_key>",
        "external_ip": "<external_ip>",
        "listen_ip": "0.0.0.0",
        "network_config_url": "https://ton-blockchain.github.io/global.config.json",
        "port": 9082
}
```

When I run it without docker, proxy_pass is default and everything work like a charm!
When I run it in docker with configuration above, the proxy is running, but  when I try to access the .adnl domain, requests don't go through, they aren't shown in container logs.
